### ISSUE TITLE
GHA script to check expired dates

### ISSUE THREAD

**Issue by yegor256** [yegor256/awesome-cfp#10]
Would be great to create a script that would parse the table in the `README.md`, extract the last column (CFP) and check whether the dates are still in the future. If one of them is in the past, the script should fail the job of GitHub Action. We will get a notification.

Let's do it after we implement #12

**Comment by yegor256** [comment]
@uchitsa this is important now, in order to keep the data valid

**Comment by uchitsa** [comment]
It works https://github.com/uchitsa/gha-check-past-dates.
For example https://github.com/uchitsa/gha-check-past-dates/blob/main/README.md

**Comment by yegor256** [comment]
@uchitsa please, submit a pull request

**Comment by yegor256** [comment]
fixed
