### ISSUE TITLE
let's keep the data in YAML format and render into Markdown on every push

### ISSUE THREAD

**Issue by yegor256** [yegor256/awesome-cfp#12]
Maybe we can keep the entire dataset in a YAML file. Then, on each `push` we configure a GHA job, that will render this YAML file into a Markdown table, put it into the README.md (replacing the existing one), and then submit a pull request with the changes to the repository.

See how it works, for example, here: https://github.com/yegor256/micromap/blob/master/.github/workflows/up.yml

**Comment by yegor256** [comment]
@uchitsa think about this, please

**Comment by uchitsa** [comment]
@yegor256 thanks, I'll do it

**Comment by yegor256** [comment]
@uchitsa will be great, if we create a Bash script that does all that: `compile.sh`. It gets a path to `.yml` file as an input and prints a Markdown table as an output. We will call this script from GHA job, saving its output to a Bash variable. Then, inject it into the `README.md`

**Comment by yegor256** [comment]
@uchitsa would be great to create a unit test (with a synthetic YAML input) for this Bash script, in order to make sure that it actually prints the right Markdown output.

**Comment by yegor256** [comment]
@uchitsa I think, this is the most important task now, since our list keeps growing and it will be just more time consuming later to turn it into YAML

**Comment by uchitsa** [comment]
@yegor256 I prepare python script to parse a yaml source and create a result md file

**Comment by yegor256** [comment]
@uchitsa don't forget to add pylint or pep8 (or both) to GHA

**Comment by yegor256** [comment]
@uchitsa thanks a lot for implementing this feature!
