### ISSUE TITLE
the `year` column duplicates the year in the title

### ISSUE THREAD

**Issue by yegor256** [yegor256/awesome-cfp#33]
Now, both the title of the conference and the `year` column have the year of the conference. It's an obvious duplication. Let's keep it only in the title and remove the extra column. Moreover, no need to show the full year, just the last two digits will be enough.

**Comment by yegor256** [comment]
@uchitsa can you please fix this

**Comment by uchitsa** [comment]
@yegor256 ok, I'll do it

**Comment by yegor256** [comment]
@uchitsa thanks!
