### ISSUE TITLE
CI actions fail

### ISSUE THREAD

**Issue by yegor256** [yegor256/awesome-cfp#53]
Currently, our actions fail, see: https://github.com/yegor256/awesome-cfp/actions/runs/9975651890/job/27565938753 Let's either remove this type of testing or make it work.

**Comment by yegor256** [comment]
@blablatdinov can you help?

**Comment by blablatdinov** [comment]
@yegor256 Yes, I see that last PR fail build and prepare fix

**Comment by yegor256** [comment]
@blablatdinov fixed, thanks!
