### ISSUE TITLE
load_generate fails in CI

### ISSUE THREAD

**Issue by yegor256** [yegor256/awesome-cfp#62]
Check this out: https://github.com/yegor256/awesome-cfp/actions/runs/10003610038/job/27650808755

Let's try to fix

**Comment by yegor256** [comment]
@blablatdinov can you help? Would be nice to prevent this from happening in the future. For some reason, no CI builds failed when I was merging pull requests, but `master` fails now.

**Comment by blablatdinov** [comment]
@yegor256 yes, problem with python version. Fixed in #63

**Comment by yegor256** [comment]
@blablatdinov thanks!
