### ISSUE TITLE
CI fails

### ISSUE THREAD

**Issue by yegor256** [yegor256/awesome-cfp#68]
See https://github.com/yegor256/awesome-cfp/actions/runs/10011263469/job/27674302736 Would be great to find the cause of the problem and fix.

**Comment by blablatdinov** [comment]
@yegor256 link 'https://www.asplos-conference.org/asplos-2025-call-for-papers' return 404 status. Which link should we replace it with?

Maybe check `cfp.yml` for each PR?

**Comment by yegor256** [comment]
@blablatdinov yes, indeed, checking CFP.yml in each PR is a perfect idea.

Here is the link: https://www.asplos-conference.org/asplos2025/cfp/

**Comment by yegor256** [comment]
@blablatdinov we still are not stable: https://github.com/yegor256/awesome-cfp/actions/workflows/tests.yml

**Comment by blablatdinov** [comment]
@yegor256 Oh, link return 404 mock it for test in #76

**Comment by yegor256** [comment]
@blablatdinov works good now, thanks!
