### ISSUE TITLE
let's split `pages` column into two: `full` + `short`

### ISSUE THREAD

**Issue by yegor256** [yegor256/awesome-cfp#8]
Would be beneficial to show whether conferences accept short papers or not, and what is the expected maximum size of them.

Also, let's add one more column: `format`. It should be either LNCS, 2C (two columns), or 1C (one column).

**Comment by yegor256** [comment]
@uchitsa please, help

**Comment by uchitsa** [comment]
@yegor256 thanks, I've got it
